name: 'Register files'
on:
  workflow_dispatch:
  repository_dispatch:
    types: [release, bugfix]
  schedule:
    - cron: '0 3 * * 1-5'
  push:
    branches:
      - main

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  register-files:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clone McStasMcXtrace/McCode
        uses: actions/checkout@v4
        with:
          repository: McStasMcXtrace/McCode
          path: mccode
          fetch-depth: 0
          fetch-tags: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: (Re)generate registry files
        run: python make_registry_files.py
